meta_product_name: "Love Island"
meta_title: "Love Island - Rent your paradise"
meta_description: "Rent a tropical island anywhere in the world"
meta_image: "Cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
